userLayers,Слои пользователя
depthCntProp,Свойста контура глубины
navCntProp,Свойста навигационного контура
wlCntProp,Свойстава контура уровня воды
userIconImport,Импорт значка пользователя
selectIcon,Выбор значка
linePlotting,Рисование линии
userObjLoad,Загрузка объекта пользователя
depthAreas,Допустимые осадки
docums,Документы
officialInfo,Официальная информация
moreInfo,Уточняющая информация
otherInfo,Прочая информация
userIcnLib,Библиотека значков пользователя
layerEditor,Редактор слоя
areaName,Название района
maxDrg,Мкс.осдк
category,Категория
info,Информация
add,Доб
delete,Удал
rename,Переим
name,Название
icon,Значок
iconDelConf,Вы хотите удалить выбранный значок из бибиотеки
iconRename,Переименование значка
nameEnter,Введите новое название
iconGrp,Группа значков
polyline,Полилиния
polygon,Полигон
navContour,Навиг.контур
depthArea,Контур глубины
depthAreaProps,Свойства контура глубины
navArea,Навигационный контур
navAreaProps,Свойства навигационного контура
cancel,Отм
save,Сохр
new,Созд
edit,Измен
changesLoose,Не сохранять изменения
visible,Виден
ok,OK
plsSpecName,Укажите имя
plsSpecUrlOrUpl,Укажите URL или загрузите файл
polylineEdit,Создание/правка полилинии
polygonEdit,Создание/правка полигона
icnGroupEdit,Создание/правка группы значков
userObj,Объект пользователя
objName,Название объекта
objNameShort,Назв.объекта
type,Тип
objNameEnter,Введите название объекта
newPolyline,Новая полилиния
newPolygon,Новый полигон
newIcon,Новый значок
newIconGrp,Новая группа значков
newBerth,Новый причал
newDepthCnt,Новый контур глубины
newNavCnt,Новый навигационный контур
newRoute,Новый маршрут
objList,Список объектов
loadUserObj,Загр польз.объекта
loadEditUserObj,Загр/ред польз.объекта
backToPrevMenu,К предыд.меню
getWeatherPredHere,Прогноз погоды в точке
objEditor,Объектный редактор
atThisPoint,В этой точке...
berth,Причал
saveObject,Сохранить объект
doNothing,Ничего не делать
settings,Настройки
baseMap,Базовая карта
overlays,Слои наложения
lat,Шир
lon,Долг
range,Дист
correction,Уточнение
id,ID
maxDraught,Макс.осадка, м
fillColor,Цвет заливки
color,Цвет
opacity,Прозрачность
polygonProps,Свойства полигона
polylineProps,Свойства полилинии
style,Стиль
lineWidth,Толщина линии
dash,Пунктир
dot,Точки
solid,Сплошная
userInfoList,Список уточнений
userInfoEdit,Редактирование уточнения
noUserInfo,Уточнений нет
param,Параметр
value,Значение
infoItemEdit,Изменение уточняющей информации
newValue,Новое значение
import,Импорт
pressToSetup,Нажмите для изменения настроек
deleteUserInfo,Удалить выделенную уточняющую информацию?
deleteAttachment,Удалить выделенное приложение?
close,Закр
applyUpdates,Применить обновления
attachments,Приложения
attachment,Приложение
objAtts,Приложения к объекту
upload,Загрузка
view,Просм
updateHistory,История обновлений
date,Дата
action,Действие
actionShort,Дйств
oldValue,Старое значение
userInfoChanged,Уточнение изменено
newAttachment,Новое приложение
delAttachment,Приложение удалено
delObject,Объект удален
newObject,Новый объект
delLayer,Слой удален
newLayer,Новый слой
draftChanged,Осадка изменена
showTimeline,Показать временную шкалу
cancel2,Отмена
timeline,Временная шкала
show,Показать
position,Координаты
navStatus,Нав.статус
aisTargets,Цели AIS
aisTargetsMT,Цели AIS (MarineTraffic)
properties,Свойства
property,Свойство
shape,Форма
waterLevels,Уровень воды
time,Время
level,Уровень
levelShort,Уров.
begin,Начало
end,Конец
query,Запросить
loading,Загружается...
le,Не более,
wmID,ID уровнемера
area,Район
noData,Нет данных
graph,График
wlChangeFor,Изменение уровня воды за период
wlLabel,Уровень воды (наведите курсор на точку на графике для получения точного значения)
bridgeProp,Контур моста
passLevel,Проходной уровень
bridge,Мост
addNewLayer,Добавление нового слоя
newWLContour,Новвя зона изм.уровня воды
wlArea,Р-н измер.уровня воды
wlMarker,Уровнемер
wlMarkerProps,Свойства уровнемера
delLayerReq,Удалить слой со всеми объектами?
iconLibrary,Библ.значков
plotOnMap,На карте
setPos,Шир/долг
baseValue,Базовое значение
baseValueOffsetFS,Смещение БЗ отн.нуля БФШ
relChange,Отн.изм
export,Экспорт
notLinked,Не привязан
areaDepth,Глубина контура
areaDepthDoc,Глуб.(док)
areaDepthAct,Глуб.(изм)
maxDraftDoc,МксОсдк(док)
maxDraftAct,МксОсдк(изм)
limitationType,Тип ограничения
limitedBelow,Не меньше
limitedAbove,Не больше
idNotSpecified,Не указан ID объекта
invalidAreaDepth,Глубина контура неверная или не указана
deviceNotSpecified,Не задано устройство
passage,Проход районов
draft,Осадка
dateTime,Дата/время
layer,Слой
m,м
cm,см
hintMode,Подсказки
off,Отключено
flash,Мерцание
onClick,По клику
battery,Бат
routes,Маршруты
speed,Скорость
start,Запуск
routeProps,Свойства маршрута
stopTime,Стоянка
stopTimeEnter,Введите время стоянки в часах
waypointEdit,Параметры точки
routeRemoveConf,Удалить выбранный маршрут?
quickAnalyze,Анализ
simulation,Симуляция
error,Ошибка
selectRouteMsg,Выберите желаемый маршрут
acceleration,Ускорение (раз)
timeQuant,Квант времени (мин)
depthMeters,Глуб(м)
state,Состояние
notApplicable,N/A
onTheWay,Переход
moored,Стоянка
paused,Приостановлен
groundingAlert,Угр.посадки на мель
depthMeters2,Глуб
propChange,ИзмСвОб
propChangeTitle,Изменение значения свойства объектов слоя
sort,Сортировка
byID,По идентификатору
byName,По имени
propsChanged,свойств было изменено
noDanger,Нет опасностей
maxAcceptableDraft,МДО
unknown,Неизвестно
